add getting seagrass + soulsoil
NovaMachina/ExNihiloSequentia pull request #139
Opened 2021-03-05 21:09 UTC by remplerus

2021-03-05 21:10 UTC, remplerus commented
seagrass from sand at level iron, and soulsoil by adding coarse dirt to witchwater in a barrel (so coarse dirt has more options now :D )

2021-03-07 23:35 UTC, NovaMachina requested changes
Please include these recipes in the data generators.

2021-03-08 17:05 UTC, NovaMachina requested changes
This is really close. Duplicate recipe names aren't allowed though.

2021-03-08 17:05 UTC, NovaMachina commented on src/main/java/novamachina/exnihilosequentia/common/datagen/ExNihiloRecipeGenerator.java
> +                .build(consumer, createSaveLocation(new ResourceLocation(ExNihiloConstants.ModIds.EX_NIHILO_SEQUENTIA, "cooked_silkworm_from_smoker")));
Duplicate recipe name

2021-03-08 17:05 UTC, NovaMachina commented on src/main/java/novamachina/exnihilosequentia/common/datagen/ExNihiloRecipeGenerator.java
> +                .build(consumer, createSaveLocation(ExNihiloBlocks.CRUCIBLE_FIRED.getId()));
Duplicate recipe name

2021-03-09 00:54 UTC, NovaMachina approved these changes

2021-03-09 00:54 UTC, merged