Add blast recipes
NovaMachina/ExNihiloSequentia pull request #147
Opened 2021-03-07 13:35 UTC by remplerus

Fix #146

2021-03-07 13:53 UTC, DreaminBoi commented
nice ty!

2021-03-07 23:37 UTC, NovaMachina requested changes
Please include recipes in the data generator.

2021-03-08 11:27 UTC, remplerus reviewed
added data gen

2021-03-08 17:10 UTC, NovaMachina approved these changes
This is really good. Duplicate recipe names aren't allowed as they will override each other.

2021-03-08 17:10 UTC, NovaMachina commented on src/main/java/novamachina/exnihilosequentia/api/datagen/AbstractRecipeGenerator.java
> +                .build(consumer, new ResourceLocation(modId, prependRecipePrefix(ore.getIngotName())));
Duplicate recipe name

2021-03-08 17:10 UTC, NovaMachina commented on src/main/java/novamachina/exnihilosequentia/common/datagen/ExNihiloRecipeGenerator.java
> +                            .build(consumer, createSaveLocation(new ResourceLocation(ExNihiloConstants.ModIds.MINECRAFT, "ingot_iron")));
Duplicate recipe name

2021-03-08 17:10 UTC, NovaMachina commented on src/main/java/novamachina/exnihilosequentia/common/datagen/ExNihiloRecipeGenerator.java
> +                            .build(consumer, createSaveLocation(new ResourceLocation(ExNihiloConstants.ModIds.MINECRAFT, "ingot_gold")));
Duplicate recipe name

2021-03-08 17:11 UTC, NovaMachina requested changes
Just need to remove the duplicate names

2021-03-09 00:55 UTC, NovaMachina approved these changes

2021-03-09 00:55 UTC, merged