Fix #265: Add campfires as a heat source
NovaMachina/ExNihiloSequentia pull request #267
Opened 2021-10-21 16:15 UTC by sam-kirby

This pull request adds support for distinguishing if a block is a heat source not only by its resource location, but also by its state. For example, a lit campfire should provide heat to a crucible, but an unlit one should not. This was not previously possible.

This is achieved by borrowing `StatePropertiesPredicate` used elsewhere in the game.

This PR also adds lit furnaces and redstone torches to the list of available heat sources.

This change was suggested at DarkPacks/SkyFactory-One#75 and I did not check here to see if it had been suggested or addressed already before looking into it. I note that PR #259 has been opened to address this, however, that PR takes a more naive approach by allowing both lit and unlit campfires to provide heat.

2021-10-21 20:08 UTC, remplerus commented
thats true. #259 addresses it, but your pr is more precise. i'll remove it out of my PR. (maybe i'll add your PR in my as i would add some more things to better address your changes to addons)

2021-10-21 20:16 UTC, remplerus commented on src/main/java/novamachina/exnihilosequentia/common/datagen/ExNihiloRecipeGenerator.java
> +        StatePropertiesPredicate lightable = StatePropertiesPredicate.Builder.properties().hasProperty(BlockStateProperties.LIT, true).build();
maybe move this in exnihilosequentia/api/datagen/AbstractRecipeGenerator and make a new function for lit recipe (something like "createLitHeatRecipes" just to make it usable in addons)

2021-10-21 20:17 UTC, remplerus approved these changes

2021-10-21 20:17 UTC, remplerus commented
oh also move this PR to 1.16-dev

2021-10-22 09:20 UTC, sam-kirby commented on src/main/java/novamachina/exnihilosequentia/common/datagen/ExNihiloRecipeGenerator.java
> +        StatePropertiesPredicate lightable = StatePropertiesPredicate.Builder.properties().hasProperty(BlockStateProperties.LIT, true).build();
As it's possible addons may want to specify other state properties such as facing, I added an overload for `AbstractRecipeGenerator#createHeatRecipes` that takes a properties argument.

2021-10-31 14:00 UTC, NovaMachina requested changes
Looks great! Just a few comments about readability.

2021-10-31 14:00 UTC, NovaMachina commented on src/main/java/novamachina/exnihilosequentia/common/crafting/serializer/HeatRecipeSerializer.java
> +        if (buffer.readBoolean()) {
This doesn't tell me what the boolean represents. Moving it to its own local variable first allows for better readability of the code.

2021-10-31 14:00 UTC, NovaMachina commented on src/main/java/novamachina/exnihilosequentia/common/crafting/serializer/HeatRecipeSerializer.java
> +            buffer.writeBoolean(true);
In addition to the above comment, this boolean seems to be random, although I can see what its being used for. Other developers / me at a later time, might not understand what this is for. A local variable or comment might be helpful.

2021-10-31 16:58 UTC, sam-kirby commented
Hopefully you find this to be more readable :)

2021-10-31 20:14 UTC, NovaMachina approved these changes

2021-10-31 20:14 UTC, merged