Create de_de.json
NovaMachina/ExNihiloSequentia pull request #321
Opened 2022-06-12 23:08 UTC by MelanX

I know, you set up Crowdin but it was much easier for me to do it that way.

2022-06-16 17:55 UTC, remplerus requested changes

2022-06-16 17:55 UTC, remplerus commented on src/main/resources/assets/exnihilosequentia/lang/de_de.json
> +  "tooltip.doll.enderman": "Füge zu einem Hexenwasserfass hinzu, um einen Enderman zu erschaffen to Spawn An Enderman",
this one need to be fixed (typo), rest seems fine

2022-06-20 17:23 UTC, remplerus approved these changes

2022-11-03 01:27 UTC, NovaMachina approved these changes

2022-11-05 14:07 UTC, merged