improvements
NovaMachina/ExNihiloSequentia pull request #40
Opened 2020-11-02 15:57 UTC by yzl210

1. Fixed a bug that can put more than 1000 solid into a crucible
2. translation and info improved:
Crucible:
![image](https://user-images.githubusercontent.com/32786985/97889165-fe955000-1d66-11eb-9952-8c8ccee100d2.png)
Barrel:
![image](https://user-images.githubusercontent.com/32786985/97889247-18369780-1d67-11eb-9017-2849cbf2adb5.png)

2020-11-04 10:56 UTC, Blackout03 commented
You should make the title reflect what is added instead of just calling it "improvements"
something like "Fixed bugs, Improved translations and Added Netherite Hammer"

2020-11-06 18:32 UTC, NovaMachina commented
I will review this as soon as I get the current feature I'm working done on.

2020-11-11 03:39 UTC, NovaMachina requested changes

2020-11-11 03:39 UTC, NovaMachina commented on src/main/java/com/novamachina/exnihilosequentia/common/block/BlockSieve.java
> +import net.minecraft.block.*;
No bulk imports.

Since you have made this pull request I have added contributing guidelines.

2020-11-11 03:39 UTC, NovaMachina commented on src/main/java/com/novamachina/exnihilosequentia/common/datagen/Recipes.java
> +import net.minecraft.data.*;
No bulk imports.

Since you have made this pull request I have added contributing guidelines.

2020-11-11 03:39 UTC, NovaMachina commented on src/main/java/com/novamachina/exnihilosequentia/common/tileentity/crucible/MeltableItemHandler.java
> +        if (crucibleHasRoom && crucibleTile.getSolidAmount() <= 1000 - amount * stack.getCount()) {
The solid amount can be variable and set by a config. Having a hardcoded 1000 disrupts this.

2020-11-11 06:46 UTC, NovaMachina approved these changes

2020-11-11 06:46 UTC, merged