added ender pearls to crushed end stone to get as a resource
NovaMachina/ExNihiloSequentia pull request #71
Opened 2020-12-04 16:58 UTC by raziel23x

2020-12-04 17:05 UTC, NovaMachina requested changes
Please also add the recipe to the data generators. Found under Recipes#registerSieveRecipes

2020-12-04 17:37 UTC, raziel23x commented
since i made i moved it from the data folder to the datagen#Recipes#registerSieveRecipes i deleted the original since you only need to datagen version

2020-12-04 23:20 UTC, raziel23x commented
> Please also add the recipe to the data generators. Found under Recipes#registerSieveRecipes

done

2020-12-06 02:57 UTC, NovaMachina approved these changes

2020-12-06 02:57 UTC, merged